#!/usr/bin/python

activate_this = '/opt/odoo/odoo-11/venv/bin/activate_this.py'
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))


import logging
import os
import sys

# so that errors are not sent to stdout
logging.basicConfig(stream=sys.stderr)

sys.path.insert(0, os.path.dirname(__file__))

from api_end_points_v11 import app as application
